"""Dice rolling, reaction, morale, encounter, saving throw, and skill check tools."""
import re
import json
import random
from pathlib import Path
import _campaign as _c


# --- Global tiered encounter tables ---------------------------------------- #
# Campaign-independent terrain tables generated by tools/build_encounter_tables.py.
_ENCOUNTER_TABLE_PATH = Path(__file__).resolve().parent.parent / "global" / "encounter_tables.json"
_encounter_cache = {"mtime": None, "data": None}

# Normalise common terrain synonyms onto the keys the global table uses.
_TERRAIN_ALIASES = {
    "mountains": "mountain", "alpine": "mountain",
    "marsh": "swamp", "marshes": "swamp", "bog": "swamp", "fen": "swamp",
    "underdark": "dungeon", "subterranean": "dungeon", "underground": "dungeon",
    "cave": "dungeon", "cavern": "dungeon",
    "sea": "ocean", "aquatic": "ocean", "water": "ocean", "coast": "ocean",
    "grassland": "plains", "grasslands": "plains", "steppe": "plains",
    "tundra": "arctic", "glacier": "arctic", "polar": "arctic",
    "city": "urban", "town": "urban", "ruins": "urban",
    "forests": "forest", "woods": "forest", "woodland": "forest",
    "hill": "hills", "jungles": "jungle", "rainforest": "jungle",
}


def _load_global_encounters():
    """Load + cache the global encounter table, reloading on file change."""
    try:
        st = _ENCOUNTER_TABLE_PATH.stat()
    except OSError:
        return None
    if _encounter_cache["mtime"] != st.st_mtime:
        try:
            _encounter_cache["data"] = json.loads(
                _ENCOUNTER_TABLE_PATH.read_text(encoding="utf-8"))
            _encounter_cache["mtime"] = st.st_mtime
        except (OSError, json.JSONDecodeError):
            return None
    return _encounter_cache["data"]


def _party_average_level(cfg) -> int:
    levels = [int(c.get("level", 0))
              for c in (cfg.get("characters", {}) or {}).values()
              if isinstance(c, dict) and c.get("level")]
    return max(1, round(sum(levels) / len(levels))) if levels else 1


def _level_to_band(level: int, bands: list) -> int:
    for i, b in enumerate(bands):
        lo, hi = b.get("party_levels", [1, 99])
        if lo <= level <= hi:
            return i
    return len(bands) - 1


def _nearest_nonempty(tiers: list, idx: int):
    """Index of the nearest tier with entries, searching outward from idx."""
    n = len(tiers)
    if n == 0:
        return None
    idx = max(0, min(n - 1, idx))
    if tiers[idx]:
        return idx
    for d in range(1, n):
        for j in (idx - d, idx + d):
            if 0 <= j < n and tiers[j]:
                return j
    return None


def _roll_on_entries(entries: list):
    """Roll d(max range) and return (entry, roll). Assumes non-empty."""
    max_val = max(e["range"][1] for e in entries)
    r = random.randint(1, max_val)
    for e in entries:
        lo, hi = e["range"]
        if lo <= r <= hi:
            return e, r
    return entries[-1], r


def register(mcp):

    @mcp.tool()
    def roll(notation: str, times: int = 1) -> dict:
        """Parse and roll dice notation: '2d6', '1d20', '4d6dl' (drop lowest), '1d8+2'.

        times: repeat the same notation N times (e.g. roll('4d6dl', times=6) for
        ability-score generation). With times=1 the return shape is
        {notation, rolls, dropped, modifier, total}. With times>1 the return is
        {notation, times, results: [<single-roll dicts>], totals: [...],
        sum, min, max} — `results` contains one entry per repeat in order."""
        original = notation.strip()

        # Parse: optional NdX, optional dl (drop lowest), optional +/-modifier
        pattern = r'^(\d*)d(\d+)(dl)?(([+-]\d+)*)$'
        m = re.match(pattern, original.lower().replace(' ', ''))
        if not m:
            return {"error": f"Cannot parse dice notation: {original}"}

        count_str, sides_str, drop_lowest, mod_str, _ = m.groups()
        count = int(count_str) if count_str else 1
        sides = int(sides_str)
        drop = drop_lowest is not None

        # Sum up modifiers
        modifier = 0
        for part in re.findall(r'[+-]\d+', mod_str or ''):
            modifier += int(part)

        if times < 1:
            return {"error": f"times must be >= 1 (got {times})"}

        def _one() -> dict:
            rolls = [random.randint(1, sides) for _ in range(count)]
            dropped = []
            if drop and count > 1:
                min_val = min(rolls)
                idx = rolls.index(min_val)
                dropped = [rolls[idx]]
                kept = rolls[:idx] + rolls[idx+1:]
            else:
                kept = rolls[:]
            return {
                "notation": original,
                "rolls": rolls,
                "dropped": dropped,
                "modifier": modifier,
                "total": sum(kept) + modifier,
            }

        if times == 1:
            return _one()

        results = [_one() for _ in range(times)]
        totals = [r["total"] for r in results]
        return {
            "notation": original,
            "times":    times,
            "results":  results,
            "totals":   totals,
            "sum":      sum(totals),
            "min":      min(totals),
            "max":      max(totals),
        }

    @mcp.tool()
    def reaction(modifier: int = 0, npc: str = "") -> dict:
        """2d10 reaction roll. Use for FIRST encounters with an unknown NPC, OR
        when a known NPC's mood is in question (pass `npc` slug to apply their
        stored disposition + faction reputation as a modifier).

        modifier: explicit situational mod (CHA reaction adj, gift offered, etc.)
        npc:      optional NPC slug — adds disposition/20 as a modifier and
                  records the result back to the NPC's history.

        Table: 2=attacks, 3-5=hostile, 6-8=uncertain, 9-11=neutral, 12+=friendly."""
        cfg = _c.load_campaign()
        total_modifier = modifier
        disposition_applied = 0
        npc_label = ""
        npc_slug  = ""

        if npc:
            slug_key = npc.lower().strip()
            npc_data = cfg.get("npcs", {}).get(slug_key)
            if not npc_data:
                # Try prefix match
                for k, v in cfg.get("npcs", {}).items():
                    if k.lower().startswith(slug_key) or v.get("label", "").lower().startswith(slug_key):
                        npc_data = v
                        slug_key = k
                        break
            if npc_data:
                disp = int(npc_data.get("disposition", 0))
                disposition_applied = disp // 20  # ±100 → ±5
                total_modifier += disposition_applied
                npc_label = npc_data.get("label", slug_key)
                npc_slug  = slug_key
                # Faction reputation modifier (added in #16)
                fac = npc_data.get("faction", "")
                if fac:
                    state = _c.load_state(cfg)
                    rep = state.get("faction_state", {}).get(fac, {}).get("reputation", 0)
                    total_modifier += rep // 25  # ±100 → ±4
            else:
                return {"error": f"NPC '{npc}' not found in campaign.json npcs."}

        r1 = random.randint(1, 10)
        r2 = random.randint(1, 10)
        raw = r1 + r2
        modified = raw + total_modifier

        if modified <= 2:
            result = "attacks"
            description = "The NPC attacks immediately."
        elif modified <= 5:
            result = "hostile"
            description = "The NPC is hostile and threatening."
        elif modified <= 8:
            result = "uncertain"
            description = "The NPC is uncertain and wary."
        elif modified <= 11:
            result = "neutral"
            description = "The NPC is neutral and indifferent."
        else:
            result = "friendly"
            description = "The NPC is friendly and well-disposed."

        # Log for traceability when an NPC slug was used
        if npc_slug:
            _c.append_event(cfg, {
                "type":  "reaction_roll",
                "slug":  npc_slug,
                "name":  npc_label,
                "result": result,
                "notes": f"reaction: {result} (raw {raw}, mod {total_modifier:+d})",
            })

        return {
            "roll":        raw,
            "modifier":    total_modifier,
            "disposition_applied": disposition_applied,
            "modified":    modified,
            "result":      result,
            "description": description,
            "npc":         npc_label,
        }

    @mcp.tool()
    def morale_check(rating: int, modifier: int = 0) -> dict:
        """2d10 morale check. If result > rating, morale breaks."""
        r1 = random.randint(1, 10)
        r2 = random.randint(1, 10)
        raw = r1 + r2
        modified = raw + modifier
        breaks = modified > rating

        if breaks:
            description = f"Morale breaks! Roll {modified} exceeds rating {rating}."
        else:
            description = f"Holds firm. Roll {modified} does not exceed rating {rating}."

        cfg = _c.load_campaign()
        _c.append_event(cfg, {
            "type":   "morale_check",
            "rating": rating,
            "modifier": modifier,
            "roll":   modified,
            "breaks": breaks,
            "notes":  description,
        })

        return {
            "roll": modified,
            "rating": rating,
            "breaks": breaks,
            "description": description,
        }

    @mcp.tool()
    def check_encounter(terrain: str) -> dict:
        """Check whether a random encounter is triggered for the given terrain.
        terrain: dungeon / wilderness / road / urban."""
        cfg = _c.load_campaign()
        freq = cfg.get("encounter_frequency", {})
        terrain_key = terrain.lower()

        defaults = {
            "dungeon":    {"die": 6,  "threshold": 1, "interval_minutes": 10},
            "wilderness": {"die": 6,  "threshold": 1, "interval_minutes": 240},
            "road":       {"die": 6,  "threshold": 1, "interval_minutes": 60},
            "urban":      {"die": 20, "threshold": 1, "interval_minutes": 120},
        }

        config = freq.get(terrain_key, defaults.get(terrain_key, {"die": 6, "threshold": 1, "interval_minutes": 60}))
        die = config.get("die", 6)
        threshold = config.get("threshold", 1)
        interval = config.get("interval_minutes", 60)

        roll_result = random.randint(1, die)
        triggered = roll_result <= threshold

        hours = interval // 60
        mins = interval % 60
        if hours and mins:
            interval_str = f"{hours}h {mins}m"
        elif hours:
            interval_str = f"{hours}h"
        else:
            interval_str = f"{mins}m"

        _c.append_event(cfg, {
            "type":      "encounter_check",
            "terrain":   terrain_key,
            "triggered": triggered,
            "notes":     f"d{die} → {roll_result}/{threshold} ({'triggered' if triggered else 'no encounter'})",
        })

        return {
            "terrain": terrain_key,
            "roll": roll_result,
            "threshold": threshold,
            "triggered": triggered,
            "interval": interval_str,
        }

    @mcp.tool()
    def determine_encounter(terrain: str, level: int = 0, dungeon_level: int = 0) -> dict:
        """Roll a tiered, terrain-appropriate random encounter.

        terrain: dungeon / forest / mountain / hills / swamp / desert / arctic /
            jungle / plains / ocean / urban / wilderness / road (synonyms like
            'mountains', 'marsh', 'underdark', 'sea' are accepted).
        level: party level used to scale difficulty. 0 = auto (average of the
            party's character levels). dungeon_level is a legacy alias for level.

        Difficulty is tiered into bands (low/mid/high/epic) by party level; the
        base band is then nudged by a 2d6 drift roll — a 2 steps down one band,
        a 12 steps up one band — clamped to bands that actually have entries.
        Per-campaign encounter_tables in campaign.json override the global
        table when present (legacy flat format still supported).
        """
        cfg = _c.load_campaign()
        terrain_key = terrain.lower().strip()
        terrain_key = _TERRAIN_ALIASES.get(terrain_key, terrain_key)

        # 1) Campaign override (legacy flat tables) wins when populated.
        overrides = cfg.get("encounter_tables", {}) or {}
        legacy_key = (f"dungeon_l{dungeon_level}"
                      if terrain_key == "dungeon" and dungeon_level else terrain_key)
        legacy = overrides.get(legacy_key) or overrides.get(terrain_key)
        if legacy:
            entry, r = _roll_on_entries(legacy)
            return {
                "terrain": terrain_key, "roll": r,
                "result": entry.get("result", "Unknown"),
                "category": entry.get("category", ""), "source": "campaign",
            }

        # 2) Global tiered table.
        data = _load_global_encounters()
        terrains = (data or {}).get("terrains", {})
        if terrain_key not in terrains:
            return {
                "roll": 0,
                "result": f"No encounter table for terrain '{terrain_key}'. "
                          f"Run tools/build_encounter_tables.py or add one to "
                          f"campaign.json encounter_tables.",
                "category": "none",
            }

        bands = data["bands"]
        eff_level = level or dungeon_level or _party_average_level(cfg)
        base = _level_to_band(eff_level, bands)

        d1, d2 = random.randint(1, 6), random.randint(1, 6)
        drift_total = d1 + d2
        step = -1 if drift_total == 2 else (1 if drift_total == 12 else 0)

        tiers = terrains[terrain_key]["tiers"]
        target = _nearest_nonempty(tiers, base + step)
        if target is None:
            return {
                "roll": 0,
                "result": f"No populated encounter tier for '{terrain_key}'.",
                "category": "none",
            }

        entry, r = _roll_on_entries(tiers[target])
        band_name = bands[target]["name"] if target < len(bands) else str(target)
        drift_word = "down" if step < 0 else ("up" if step > 0 else "none")

        _c.append_event(cfg, {
            "type": "encounter",
            "terrain": terrain_key,
            "notes": f"{band_name} tier (party L{eff_level}, drift {drift_word} "
                     f"on 2d6={drift_total}) → {entry.get('result', '?')}",
        })

        return {
            "terrain": terrain_key,
            "party_level": eff_level,
            "tier": band_name,
            "drift": drift_word,
            "drift_roll": drift_total,
            "roll": r,
            "result": entry.get("result", "Unknown"),
            "category": entry.get("category", ""),
            "monster": entry.get("monster", ""),
            "source": "global",
        }

    @mcp.tool()
    def surprise_check(party_modifier: int = 0, enemy_modifier: int = 0) -> dict:
        """Roll surprise for both sides at the start of an encounter (PHB Ch. 9).
        Each side rolls 1d10 separately. A roll of 1–2 = surprised (default threshold).
        Surprised side loses one segment (10 segments = 1 round) of action and may not
        use shields. Modifiers shift the threshold (positive = harder to surprise; e.g.
        Ranger imposes -3 on enemies trying to surprise the party in wilderness).

        party_modifier: +N to enemy roll's surprise threshold for the party (i.e.
                        threshold becomes 2 - N for the enemy; rangers/elves/etc.)
        enemy_modifier: +N to party's surprise threshold (party harder to surprise
                        the enemy when sneaking, etc.)

        Returns who is surprised and by how many segments."""
        # Threshold = 2 by default. A side is surprised if their d10 ≤ threshold.
        # The opposing side's modifier *raises their threshold* (more likely surprised).
        party_d10 = random.randint(1, 10)
        enemy_d10 = random.randint(1, 10)

        party_threshold = max(0, 2 - enemy_modifier)
        enemy_threshold = max(0, 2 - party_modifier)

        party_surprised = party_d10 <= party_threshold
        enemy_surprised = enemy_d10 <= enemy_threshold

        # Segments lost: surprised side loses (threshold - roll + 1) segments per
        # the looser DMG reading; we default to 1 segment (PHB simplified).
        party_segments = max(0, party_threshold - party_d10 + 1) if party_surprised else 0
        enemy_segments = max(0, enemy_threshold - enemy_d10 + 1) if enemy_surprised else 0

        if party_surprised and enemy_surprised:
            description = "Both sides surprised — encounter begins simultaneously, no advantage."
        elif party_surprised:
            description = f"Party is surprised. Enemy acts freely for {party_segments} segment(s)."
        elif enemy_surprised:
            description = f"Enemy is surprised. Party acts freely for {enemy_segments} segment(s)."
        else:
            description = "Neither side surprised — roll initiative normally."

        cfg = _c.load_campaign()
        _c.append_event(cfg, {
            "type":  "surprise_check",
            "party_surprised": party_surprised,
            "enemy_surprised": enemy_surprised,
            "notes": description,
        })

        return {
            "party_roll":       party_d10,
            "enemy_roll":       enemy_d10,
            "party_threshold":  party_threshold,
            "enemy_threshold":  enemy_threshold,
            "party_surprised":  party_surprised,
            "enemy_surprised":  enemy_surprised,
            "party_segments_lost": party_segments,
            "enemy_segments_lost": enemy_segments,
            "description":      description,
        }

    @mcp.tool()
    def saving_throw(character: str, save_type: str) -> dict:
        """Roll a saving throw for a character.
        save_type: para/paralysis/poison/death | rsw/rod/staff/wand | poly/polymorph/petrify | breath/bw | spell/magic"""
        cfg = _c.load_campaign()

        save_aliases = {
            "para": 0, "paralysis": 0, "poison": 0, "death": 0,
            "rsw": 1, "rod": 1, "staff": 1, "wand": 1,
            "poly": 2, "polymorph": 2, "petrify": 2,
            "breath": 3, "bw": 3,
            "spell": 4, "magic": 4,
        }
        save_names = ["Paralysis/Poison/Death", "Rod/Staff/Wand", "Polymorph/Petrify", "Breath Weapon", "Spell/Magic"]

        key, char = _c.char_key_for(cfg, character)
        if key is None:
            return {"error": f"Character '{character}' not found."}

        idx = save_aliases.get(save_type.lower())
        if idx is None:
            return {"error": f"Unknown save type '{save_type}'. Use: para, rsw, poly, breath, spell."}

        saves_norm = _c.normalize_saves(char.get("saves"))
        if saves_norm:
            by_type = {s["type"]: s["value"] for s in saves_norm}
            target = by_type.get(_c.SAVE_TYPES[idx], [16, 18, 17, 20, 19][idx])
        else:
            target = [16, 18, 17, 20, 19][idx]
        roll_result = random.randint(1, 20)
        success = roll_result >= target

        return {
            "character": char.get("label", key),
            "save": save_names[idx],
            "roll": roll_result,
            "target": target,
            "success": success,
        }

    @mcp.tool()
    def monster_saving_throw(name: str, save_type: str, hd: float,
                             hd_bonus: int = 0, intelligent: bool = True) -> dict:
        """Roll a saving throw for a monster by Hit Dice (DMG Table 46, Warrior group).

        Use for any combatant added via add_combatant() that has no character file.
        Per the DMG (global/reference/dmg.txt, Table 46) monsters save on the Warrior
        table at a level set by their Hit Dice:
          - Every creature saves vs paralysis/poison/death at level = HD.
          - Intelligent creatures (animal INT or better) save vs everything at level = HD.
          - Non-intelligent creatures (INT 0) save vs all *other* attacks at level = HD/2,
            rounded up.
          - A hit-dice bonus (the "+N" in e.g. 5+6) adds one level per 4 points or fraction.

        name: label for the rolling creature (e.g. "Ogre #2") — display only, no file needed.
        save_type: para/paralysis/poison/death | rsw/rod/staff/wand | poly/polymorph/petrify | breath/bw | spell/magic
        hd: number of Hit Dice (pass the dice count; e.g. 5 for a 5+6 ogre, with hd_bonus=6).
        hd_bonus: the "+N"/"-N" modifier on the HD (6 for 5+6, -1 for 1-1; default 0).
        intelligent: set False only for INT 0 (Non-intelligent) creatures; True otherwise."""
        save_aliases = {
            "para": 0, "paralysis": 0, "poison": 0, "death": 0,
            "rsw": 1, "rod": 1, "staff": 1, "wand": 1,
            "poly": 2, "polymorph": 2, "petrify": 2,
            "breath": 3, "bw": 3,
            "spell": 4, "magic": 4,
        }
        save_names = ["Paralysis/Poison/Death", "Rod/Staff/Wand", "Polymorph/Petrify", "Breath Weapon", "Spell/Magic"]

        idx = save_aliases.get(save_type.lower())
        if idx is None:
            return {"error": f"Unknown save type '{save_type}'. Use: para, rsw, poly, breath, spell."}

        # DMG Table 46 — Warrior group. (cap, [para/poison/death, rsw, petrify/polymorph, breath, spell])
        # cap = highest character level in the band; first row whose cap >= level wins.
        warrior_saves = [
            (0,  [16, 18, 17, 20, 19]),
            (2,  [14, 16, 15, 17, 17]),
            (4,  [13, 15, 14, 16, 16]),
            (6,  [11, 13, 12, 13, 14]),
            (8,  [10, 12, 11, 12, 13]),
            (10, [8, 10, 9, 9, 11]),
            (12, [7, 9, 8, 8, 10]),
            (14, [5, 7, 6, 5, 8]),
            (16, [4, 6, 5, 4, 7]),
            (99, [3, 5, 4, 4, 6]),
        ]

        # Effective HD level: dice count + one level per 4 bonus points (round up).
        base_level = max(0, int(hd))
        if hd_bonus > 0:
            base_level += (hd_bonus + 3) // 4  # ceil(hd_bonus / 4)
        # Poison/death always saves at full HD; non-intelligent halve all other saves (round up).
        if idx == 0 or intelligent:
            level = base_level
        else:
            level = (base_level + 1) // 2  # ceil(base_level / 2)

        target = next(cols for cap, cols in warrior_saves if level <= cap)[idx]
        roll_result = random.randint(1, 20)
        success = roll_result >= target

        hd_str = f"{int(hd)}"
        if hd_bonus > 0:
            hd_str += f"+{hd_bonus}"
        elif hd_bonus < 0:
            hd_str += f"{hd_bonus}"

        return {
            "character": name,
            "save": save_names[idx],
            "hd": hd_str,
            "save_as_level": level,
            "roll": roll_result,
            "target": target,
            "success": success,
        }

    @mcp.tool()
    def system_shock(character: str) -> dict:
        """Roll system shock for a character (PHB Table 3, CON-driven).
        Required after polymorph, petrification, raise dead, or any massive
        magical/biological transformation. Failure = die instantly.

        Pulls CON from ability_scores. Returns roll, CON, target %, and pass/fail."""
        # PHB Table 3: System Shock % by CON.
        SHOCK = {3: 35, 4: 40, 5: 45, 6: 50, 7: 55, 8: 60, 9: 65, 10: 70,
                 11: 75, 12: 80, 13: 85, 14: 88, 15: 90, 16: 95, 17: 97,
                 18: 99, 19: 99, 20: 99, 21: 99, 22: 99, 23: 99, 24: 99}

        cfg = _c.load_campaign()
        key, char = _c.char_key_for(cfg, character)
        if key is None:
            return {"error": f"Character '{character}' not found."}

        ab = char.get("ability_scores") or {}
        con = int(ab.get("con", 10))
        target = SHOCK.get(con, 70)
        roll = random.randint(1, 100)
        success = roll <= target

        return {
            "character":   char.get("label", key),
            "con":         con,
            "target":      target,
            "roll":        roll,
            "success":     success,
            "description": (
                f"{char.get('label', key)} survives the shock — roll {roll} ≤ {target}." if success
                else f"{char.get('label', key)} dies of system shock — roll {roll} > {target}."
            ),
        }

    @mcp.tool()
    def resurrection_check(character: str) -> dict:
        """Roll resurrection survival (PHB Table 3, CON-driven).
        Each failed or successful attempt reduces the character's CON by 1
        permanently — when CON hits 0 they cannot be raised again.

        Updates ability_scores.con on success or failure (the cost is paid
        regardless). Failure → the character is unrecoverably dead by this method."""
        # PHB Table 3: Resurrection Survival % by CON.
        RESURRECT = {3: 40, 4: 45, 5: 50, 6: 55, 7: 60, 8: 65, 9: 70, 10: 75,
                     11: 80, 12: 85, 13: 90, 14: 92, 15: 94, 16: 96, 17: 98,
                     18: 100, 19: 100, 20: 100}

        cfg = _c.load_campaign()
        key, char = _c.char_key_for(cfg, character)
        if key is None:
            return {"error": f"Character '{character}' not found."}

        ab = char.setdefault("ability_scores", {})
        con = int(ab.get("con", 10))
        if con <= 0:
            return {"error": f"{char.get('label', key)} has CON {con} — beyond resurrection."}

        target = RESURRECT.get(con, 75)
        roll = random.randint(1, 100)
        success = roll <= target

        # Permanent CON cost
        ab["con"] = con - 1
        _c.save_campaign(cfg)

        return {
            "character":   char.get("label", key),
            "con_before":  con,
            "con_after":   con - 1,
            "target":      target,
            "roll":        roll,
            "success":     success,
            "description": (
                f"Resurrection succeeds — roll {roll} ≤ {target}. CON {con} → {con-1}." if success
                else f"Resurrection fails — roll {roll} > {target}. The body cannot be recalled. CON {con} → {con-1} (cost paid regardless)."
            ),
        }

    @mcp.tool()
    def skill_check(character: str, skill: str) -> dict:
        """Roll a thieving or special skill check (percentile).
        Partial match on skill key name."""
        cfg = _c.load_campaign()

        key, char = _c.char_key_for(cfg, character)
        if key is None:
            return {"error": f"Character '{character}' not found."}

        skills = char.get("skills", {})
        skill_lower = skill.lower()

        # Partial match
        matched_key = None
        for k in skills:
            if skill_lower in k.lower():
                matched_key = k
                break

        if matched_key is None:
            return {"error": f"Skill '{skill}' not found for {char.get('label', key)}. Available: {list(skills.keys())}"}

        target = skills[matched_key]
        roll_result = random.randint(1, 100)
        success = roll_result <= target

        return {
            "character": char.get("label", key),
            "skill": matched_key,
            "roll": roll_result,
            "target": target,
            "success": success,
        }
